# デフォルトのシェル
# set -g default-shell /bin/bash

# デフォルトの端末色設定 (tmux内で256色を表示可能にする)
set -g default-terminal "tmux-256color" #"screen"

set -g extended-keys on #always
set -g allow-passthrough on
set -g focus-events on
set -as terminal-features ',*:RGB:usstyle:cstyle:ccolour:clipboard:strikethrough:sync:title:hyperlinks:extkeys'

# # コマンドの入力待ち時間（ミリ秒）
set -g escape-time 0 #(500)
# # --- キーバインド関連 ---
set -g mode-keys vi
set -g status-keys vi
#
# # プレフィックスキー (デフォルトは Ctrl+b)
# set -g prefix C-s
# unbind-key C-b

bind -n 'M-c' new-window 
bind -n 'M-q' kill-pane
bind -n 'M-x' kill-pane
bind -n 'M-s' split-pane -v
bind -n 'M-v' split-pane -h

bind -n 'M-n' next-window
bind -n 'M-p' previous-window


# bind -n 'M-h' select-pane -L
# bind -n 'M-j' select-pane -D
# bind -n 'M-k' select-pane -U
# bind -n 'M-l' select-pane -R

bind -n 'M-S-h' resize-pane -L
bind -n 'M-S-j' resize-pane -D
bind -n 'M-S-k' resize-pane -U
bind -n 'M-S-l' resize-pane -R



bind r source-file ~/.tmux.conf \; display "Reloaded!"
is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|l?n?vim?x?)(diff)?$'"

bind-key -T copy-mode-vi y \
  send-keys -X copy-pipe-and-cancel "wl-copy"

bind-key -T copy-mode-vi MouseDragEnd1Pane \
  send-keys -X copy-pipe-and-cancel "wl-copy"

bind-key -n MouseDown3Pane if-shell "$is_vim" "send-keys -M" \
  "run-shell 'wl-paste --no-newline | tmux load-buffer - && tmux paste-buffer -p'"

bind-key -n C-r if-shell "$is_vim" "send-keys C-r" "send-keys C-l"

bind-key -n M-h if-shell "$is_vim" "send-keys C-w h" "select-pane -L"
bind-key -n M-j if-shell "$is_vim" "send-keys C-w j" "select-pane -D"
bind-key -n M-k if-shell "$is_vim" "send-keys C-w k" "select-pane -U"
bind-key -n M-l if-shell "$is_vim" "send-keys C-w l" "select-pane -R"
bind-key -n C-Space if-shell "$is_vim" 'send-keys C-Space'  'select-pane -l'
bind-key -T copy-mode-vi M-h select-pane -L
bind-key -T copy-mode-vi M-j select-pane -D
bind-key -T copy-mode-vi M-k select-pane -U
bind-key -T copy-mode-vi M-l select-pane -R
bind-key -T copy-mode-vi C-Space select-pane -l
set -g status off
set -g mouse on #(off)

